# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/RMX3242/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/samsung/a05m-mtk_connectivity

PRODUCT_COPY_FILES += \
    vendor/samsung/a05m-mtk_connectivity/proprietary/lib/modules/bt_drv_connac1x.ko:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/modules/bt_drv_connac1x.ko \
    vendor/samsung/a05m-mtk_connectivity/proprietary/lib/modules/connfem.ko:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/modules/connfem.ko \
    vendor/samsung/a05m-mtk_connectivity/proprietary/lib/modules/fmradio_drv_mt6631.ko:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/modules/fmradio_drv_mt6631.ko \
    vendor/samsung/a05m-mtk_connectivity/proprietary/lib/modules/fpsgo.ko:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/modules/fpsgo.ko \
    vendor/samsung/a05m-mtk_connectivity/proprietary/lib/modules/gps_drv.ko:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/modules/gps_drv.ko \
    vendor/samsung/a05m-mtk_connectivity/proprietary/lib/modules/met.ko:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/modules/met.ko \
    vendor/samsung/a05m-mtk_connectivity/proprietary/lib/modules/trace_mmstat.ko:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/modules/trace_mmstat.ko \
    vendor/samsung/a05m-mtk_connectivity/proprietary/lib/modules/udc_lib.ko:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/modules/udc_lib.ko \
    vendor/samsung/a05m-mtk_connectivity/proprietary/lib/modules/wlan_drv_gen4m.ko:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/modules/wlan_drv_gen4m.ko \
    vendor/samsung/a05m-mtk_connectivity/proprietary/lib/modules/wmt_chrdev_wifi.ko:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/modules/wmt_chrdev_wifi.ko \
    vendor/samsung/a05m-mtk_connectivity/proprietary/lib/modules/wmt_drv.ko:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/modules/wmt_drv.ko \
    vendor/samsung/a05m-mtk_connectivity/proprietary/lib/modules/modules.alias:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/modules/modules.alias \
    vendor/samsung/a05m-mtk_connectivity/proprietary/lib/modules/modules.load:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/modules/modules.load \
    vendor/samsung/a05m-mtk_connectivity/proprietary/lib/modules/modules.softdep:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/modules/modules.softdep \
    vendor/samsung/a05m-mtk_connectivity/proprietary/lib/modules/modules.dep:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/modules/modules.dep \
    vendor/samsung/a05m-mtk_connectivity/proprietary/etc/init/init.mtk.connect.rc:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/init/init.mtk.connect.rc
 

